import java.awt.Color;

public class TurtleWorld
{
    public static void main(String args[])
    {
        World turtleWorld = new World();
        Turtle turtle = new Turtle(turtleWorld);
        turtle.setPenColor(Color.RED);
        turtle.penDown();
        turtle.forward(50);
        turtle.penUp();
        turtle.forward(5);
        turtle.penDown();
        turtle.setPenColor(Color.BLUE);
        turtle.forward(50);
        turtle.hide();
        turtle.turn(90);
        turtle.forward(100);
        turtle.setPenColor(Color.GREEN);
        turtle.penDown();
        turtle.forward(50);
        turtle.penUp();
        turtle.forward(5);
        turtle.penDown();
        turtle.setPenColor(Color.BLUE);
        turtle.forward(50);
        turtle.hide();
        turtle.turn(90);
        turtle.forward(100);
        turtle.setPenColor(Color.GREEN);
        turtle.penDown();
        turtle.forward(50);
        turtle.setPenColor(Color.RED);
        turtle.penDown();
        turtle.forward(50);
        turtle.penUp();
        turtle.forward(5);
        turtle.penDown();
        turtle.setPenColor(Color.BLUE);
        turtle.forward(50);
        turtle.turn(30);
        turtle.forward(100);
        turtle.setPenColor(Color.GREEN);
        turtle.penDown();
        turtle.forward(50);
        turtle.setPenColor(Color.RED);
        turtle.penDown();
        turtle.forward(50);
        turtle.penUp();
        turtle.forward(5);
        turtle.penDown();
        turtle.setPenColor(Color.BLUE);
        turtle.forward(50);
        turtle.turn(150);
        turtle.forward(100);
        turtle.setPenColor(Color.GREEN);
        turtle.penDown();
        turtle.forward(50);
        turtle.setPenColor(Color.RED);
        turtle.penDown();
        turtle.forward(50);
        turtle.penUp();
        turtle.forward(5);
        turtle.penDown();
        turtle.setPenColor(Color.BLUE);
        turtle.forward(50);
    }
}
